# Generated by Django 5.0.6 on 2024-05-20 11:54

import datetime

import core.constants
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("data", "0003_remove_objectsport_object_sport_indoor_outdoor_and_more"),
        ("info", "0004_remove_favoriteevents_events_and_more"),
        ("users", "0002_remove_users_passport_issued_by_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Events",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_title",
                    models.CharField(
                        max_length=core.constants.FieldLength["MAX_LENGTH_TITLE"],
                        verbose_name="Название мероприятия",
                    ),
                ),
                (
                    "event_image",
                    models.ImageField(
                        upload_to="images/events/",
                        verbose_name="Изображение мероприятия",
                    ),
                ),
                (
                    "event_start_date",
                    models.DateField(
                        default=datetime.date.today,
                        verbose_name="Дата начала мероприятия",
                    ),
                ),
                (
                    "event_end_date",
                    models.DateField(
                        default=datetime.date.today,
                        verbose_name="Дата окончания мероприятия",
                    ),
                ),
                (
                    "event_information",
                    models.TextField(verbose_name="Информация о мероприятии"),
                ),
                (
                    "event_qr_code",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images//events/qr_codes/",
                        verbose_name="QR-код",
                    ),
                ),
                (
                    "event_city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events_city",
                        to="data.cities",
                        verbose_name="Город",
                    ),
                ),
                (
                    "event_curator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events_curator",
                        to="users.users",
                        verbose_name="Организатор мероприятия",
                    ),
                ),
                (
                    "event_disciplines",
                    models.ManyToManyField(
                        to="data.disciplines", verbose_name="Дисциплины"
                    ),
                ),
                (
                    "event_partner",
                    models.ManyToManyField(
                        to="data.partners", verbose_name="Партнеры мероприятия"
                    ),
                ),
                (
                    "event_regional_division",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events_regional_division",
                        to="info.regionaldivisions",
                        verbose_name="Региональное отделение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Мероприятие",
                "verbose_name_plural": "Мероприятия",
            },
        ),
        migrations.CreateModel(
            name="FavoriteEvents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_favorite",
                        to="events.events",
                        verbose_name="мероприятие",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants_favorite",
                        to="users.users",
                        verbose_name="участник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Избранное мероприятие",
                "verbose_name_plural": "Избранные мероприятия",
            },
        ),
        migrations.CreateModel(
            name="RegisteredEvents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_registered",
                        to="events.events",
                        verbose_name="Мероприятие",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participant_registered",
                        to="users.users",
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Регистрация",
                "verbose_name_plural": "Регистрации",
            },
        ),
        migrations.AddConstraint(
            model_name="favoriteevents",
            constraint=models.UniqueConstraint(
                fields=("user", "event"), name="user_event"
            ),
        ),
        migrations.AddConstraint(
            model_name="registeredevents",
            constraint=models.UniqueConstraint(
                fields=("event", "user"), name="event_user"
            ),
        ),
    ]
