# Generated by Django 5.0.6 on 2024-05-26 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("events", "0001_initial"),
        ("info", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="events",
            name="event_curator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events_curator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Организатор мероприятия",
            ),
        ),
        migrations.AddField(
            model_name="events",
            name="event_disciplines",
            field=models.ManyToManyField(
                to="info.disciplines", verbose_name="Дисциплины"
            ),
        ),
        migrations.AddField(
            model_name="events",
            name="event_partner",
            field=models.ManyToManyField(
                to="info.partners", verbose_name="Партнеры мероприятия"
            ),
        ),
        migrations.AddField(
            model_name="events",
            name="event_regional_division",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events_regional_division",
                to="info.regionaldivisions",
                verbose_name="Региональное отделение",
            ),
        ),
        migrations.AddField(
            model_name="favoriteevents",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_favorite",
                to="events.events",
                verbose_name="мероприятие",
            ),
        ),
        migrations.AddField(
            model_name="favoriteevents",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participants_favorite",
                to=settings.AUTH_USER_MODEL,
                verbose_name="участник",
            ),
        ),
        migrations.AddField(
            model_name="registeredevents",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_registered",
                to="events.events",
                verbose_name="Мероприятие",
            ),
        ),
        migrations.AddField(
            model_name="registeredevents",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participant_registered",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddConstraint(
            model_name="favoriteevents",
            constraint=models.UniqueConstraint(
                fields=("user", "event"), name="user_event"
            ),
        ),
        migrations.AddConstraint(
            model_name="registeredevents",
            constraint=models.UniqueConstraint(
                fields=("event", "user"), name="event_user"
            ),
        ),
    ]
