# Generated by Django 5.0.6 on 2024-05-20 15:25

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_alter_events_event_qr_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="events",
            name="event_end_date",
            field=models.DateTimeField(
                default=datetime.date.today, verbose_name="Дата окончания мероприятия"
            ),
        ),
        migrations.AlterField(
            model_name="events",
            name="event_start_date",
            field=models.DateTimeField(
                default=datetime.date.today, verbose_name="Дата начала мероприятия"
            ),
        ),
    ]
