# Generated by Django 5.0.6 on 2024-05-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_alter_events_event_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="events",
            name="event_ics_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="images/events/ics_files/",
                verbose_name="Файл календаря",
            ),
        ),
    ]
