# Generated by Django 5.0.6 on 2024-05-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0004_events_event_ics_file"),
        ("info", "0005_disciplines_objectsportimage_partners_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="events",
            name="event_disciplines",
            field=models.ManyToManyField(
                to="info.disciplines", verbose_name="Дисциплины"
            ),
        ),
        migrations.AlterField(
            model_name="events",
            name="event_partner",
            field=models.ManyToManyField(
                to="info.partners", verbose_name="Партнеры мероприятия"
            ),
        ),
    ]
