# Generated by Django 5.0.6 on 2024-05-20 19:14

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0005_alter_events_event_disciplines_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="events",
            name="event_is_disabled",
            field=models.BooleanField(
                default=False, verbose_name="Для людей с\xa0ограниченными возможностями"
            ),
        ),
        migrations.AddField(
            model_name="events",
            name="event_is_food",
            field=models.BooleanField(
                default=False, verbose_name="Можно ли со своей едой"
            ),
        ),
        migrations.AddField(
            model_name="events",
            name="event_is_pets",
            field=models.BooleanField(default=False, verbose_name="Можно с животными"),
        ),
        migrations.AddField(
            model_name="events",
            name="event_is_wc",
            field=models.BooleanField(default=False, verbose_name="Есть ли туалет"),
        ),
        migrations.AlterField(
            model_name="events",
            name="event_end_date",
            field=models.DateTimeField(
                default=datetime.datetime.now, verbose_name="Дата окончания мероприятия"
            ),
        ),
        migrations.AlterField(
            model_name="events",
            name="event_start_date",
            field=models.DateTimeField(
                default=datetime.datetime.now, verbose_name="Дата начала мероприятия"
            ),
        ),
    ]
