# Generated by Django 5.0.6 on 2024-05-26 18:47

import core.constants
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Regions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "region_title",
                    models.CharField(
                        max_length=core.constants.FieldLength["MAX_LENGTH_TITLE"],
                        verbose_name="Название региона",
                    ),
                ),
            ],
            options={
                "verbose_name": "Регион",
                "verbose_name_plural": "Регионы",
            },
        ),
        migrations.CreateModel(
            name="Cities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "city_title",
                    models.CharField(
                        max_length=core.constants.FieldLength["MAX_LENGTH_TITLE"],
                        verbose_name="Название города",
                    ),
                ),
                (
                    "city_region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="data.regions",
                        verbose_name="Регион",
                    ),
                ),
            ],
            options={
                "verbose_name": "Город",
                "verbose_name_plural": "Города",
            },
        ),
    ]
