# Generated by Django 5.0.6 on 2024-05-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_title', models.CharField(max_length=100, verbose_name='Название города')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Disciplines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplines_title', models.CharField(max_length=100, verbose_name='Название дисциплины')),
                ('disciplines_image', models.ImageField(upload_to='images/disciplines/', verbose_name='Фотография дисциплины')),
                ('disciplines_video_url', models.URLField(verbose_name='Ссылка на видео')),
                ('disciplines_information', models.TextField(verbose_name='Информация о дисциплине')),
            ],
            options={
                'verbose_name': 'Дисциплина',
                'verbose_name_plural': 'Дисциплины',
            },
        ),
        migrations.CreateModel(
            name='ObjectSportImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_sport_image', models.ImageField(upload_to='images/object_sport/', verbose_name='Фотография спортивного обьекта')),
            ],
            options={
                'verbose_name': 'Фотография спортивного обьекта',
                'verbose_name_plural': 'Фотография спортивных обьектов',
            },
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partners_title', models.CharField(max_length=100, verbose_name='Название партнера')),
                ('partners_category', models.CharField(choices=[('strategic', 'Стратегические партнеры'), ('organizational', 'Организационные партнеры'), ('regional', 'Региональные партнеры'), ('general', 'Генеральные партнеры')], default='strategic', max_length=100, verbose_name='Категория партнера')),
                ('partners_logo', models.ImageField(upload_to='images/partners/', verbose_name='Логотип партнера')),
                ('partners_url', models.URLField(verbose_name='Ссылка на сайт партнера')),
            ],
            options={
                'verbose_name': 'Партнер',
                'verbose_name_plural': 'Партнеры',
            },
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_title', models.CharField(max_length=100, verbose_name='Название региона')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
            },
        ),
        migrations.CreateModel(
            name='ObjectSport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_sport_title', models.CharField(max_length=100, verbose_name='Название спортивного объекта')),
                ('video_object_sport', models.URLField(verbose_name='Ссылка на видео объекта спорта')),
                ('object_sport_indoor_outdoor', models.CharField(max_length=10, verbose_name='Помещение (закрытое/открытое)')),
                ('object_sport_info', models.CharField(max_length=100, verbose_name='Описание объекта')),
                ('object_sport_address', models.CharField(max_length=100, verbose_name='Адрес обьекта')),
                ('object_sport_image', models.ManyToManyField(to='data.objectsportimage', verbose_name='Фотография спортивного обьекта')),
            ],
            options={
                'verbose_name': 'Спортивный объект',
                'verbose_name_plural': 'Спортивные объекты',
            },
        ),
    ]
