# Generated by Django 5.0.6 on 2024-05-20 11:50

import core.constants
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0002_rename_video_object_sport_objectsport_object_sport_video"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="objectsport",
            name="object_sport_indoor_outdoor",
        ),
        migrations.AddField(
            model_name="cities",
            name="city_region",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="data.regions",
                verbose_name="Регион",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="objectsport",
            name="object_disciplines",
            field=models.ManyToManyField(
                to="data.disciplines", verbose_name="Дисциплины объекта"
            ),
        ),
        migrations.AddField(
            model_name="objectsport",
            name="object_sport_type",
            field=models.CharField(
                choices=[("outdoor", "Открытое"), ("indoor", "Закрытое")],
                default="indoor",
                max_length=core.constants.FieldLength["MAX_LENGTH_TITLE"],
                verbose_name="Помещение (закрытое/открытое)",
            ),
        ),
        migrations.AlterField(
            model_name="cities",
            name="city_title",
            field=models.CharField(
                max_length=core.constants.FieldLength["MAX_LENGTH_TITLE"],
                verbose_name="Название города",
            ),
        ),
        migrations.AlterField(
            model_name="disciplines",
            name="disciplines_title",
            field=models.CharField(
                max_length=core.constants.FieldLength["MAX_LENGTH_TITLE"],
                verbose_name="Название дисциплины",
            ),
        ),
        migrations.AlterField(
            model_name="objectsport",
            name="object_sport_address",
            field=models.CharField(
                max_length=core.constants.FieldLength["MAX_LENGTH_TITLE"],
                verbose_name="Адрес обьекта",
            ),
        ),
        migrations.AlterField(
            model_name="objectsport",
            name="object_sport_info",
            field=models.TextField(verbose_name="Описание объекта"),
        ),
        migrations.AlterField(
            model_name="objectsport",
            name="object_sport_title",
            field=models.CharField(
                max_length=core.constants.FieldLength["MAX_LENGTH_TITLE"],
                verbose_name="Название спортивного объекта",
            ),
        ),
        migrations.AlterField(
            model_name="partners",
            name="partners_category",
            field=models.CharField(
                choices=[
                    ("strategic", "Стратегические партнеры"),
                    ("organizational", "Организационные партнеры"),
                    ("regional", "Региональные партнеры"),
                    ("general", "Генеральные партнеры"),
                ],
                default="strategic",
                max_length=core.constants.FieldLength["MAX_LENGTH_TITLE"],
                verbose_name="Категория партнера",
            ),
        ),
        migrations.AlterField(
            model_name="partners",
            name="partners_title",
            field=models.CharField(
                max_length=core.constants.FieldLength["MAX_LENGTH_TITLE"],
                verbose_name="Название партнера",
            ),
        ),
        migrations.AlterField(
            model_name="regions",
            name="region_title",
            field=models.CharField(
                max_length=core.constants.FieldLength["MAX_LENGTH_TITLE"],
                verbose_name="Название региона",
            ),
        ),
    ]
