# Generated by Django 5.0.6 on 2024-05-20 17:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0003_remove_objectsport_object_sport_indoor_outdoor_and_more"),
        ("events", "0005_alter_events_event_disciplines_and_more"),
        ("info", "0005_disciplines_objectsportimage_partners_and_more"),
        ("news", "0002_alter_news_news_disciplines_alter_news_news_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="objectsport",
            name="object_disciplines",
        ),
        migrations.RemoveField(
            model_name="objectsport",
            name="object_sport_image",
        ),
        migrations.DeleteModel(
            name="Partners",
        ),
        migrations.DeleteModel(
            name="Disciplines",
        ),
        migrations.DeleteModel(
            name="ObjectSport",
        ),
        migrations.DeleteModel(
            name="ObjectSportImage",
        ),
    ]
