# Generated by Django 5.0.6 on 2024-05-16 18:01

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events_title', models.CharField(max_length=100, verbose_name='Название мероприятия')),
                ('events_image', models.ImageField(upload_to='images/events/', verbose_name='Изображение мероприятия')),
                ('events_date', models.DateField(default=datetime.date.today, verbose_name='Дата мероприятия')),
                ('events_information', models.TextField(verbose_name='Информация о мероприятии')),
                ('events_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.cities', verbose_name='Город')),
                ('events_curator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users', verbose_name='Организатор мероприятия')),
                ('events_disciplines', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.disciplines', verbose_name='Дисциплины')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.CreateModel(
            name='FavoriteEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.events', verbose_name='Мероприятие')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Избранное мероприятие',
                'verbose_name_plural': 'Избранные мероприятия',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=100, verbose_name='Название новости')),
                ('news_image', models.ImageField(upload_to='images/news/', verbose_name='Фотография')),
                ('news_date', models.DateField(verbose_name='Дата')),
                ('news_text', models.TextField(verbose_name='Описание новости')),
                ('autors', models.ManyToManyField(to='users.users', verbose_name='Авторы')),
                ('disciplines', models.ManyToManyField(to='data.disciplines', verbose_name='Дисциплины')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='FollowersNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users', verbose_name='Пользователь')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.news', verbose_name='Новости')),
            ],
            options={
                'verbose_name': 'Подписчик',
                'verbose_name_plural': 'Подписчики',
            },
        ),
        migrations.CreateModel(
            name='RegionalDivisions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regional_divisions_title', models.CharField(max_length=100, verbose_name='Название регионального отделения')),
                ('regional_divisions_image', models.ImageField(upload_to='images/regional_divisions/', verbose_name='Фотографии региональных отделений')),
                ('regional_divisions_information', models.TextField(verbose_name='Общая информация регионального отделения')),
                ('regional_divisions_info', models.TextField(verbose_name='Описание регионального отделения')),
                ('regional_divisions_curators', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users', verbose_name='Руководитель регионального отделения')),
                ('regional_divisions_disciplines', models.ManyToManyField(to='data.disciplines', verbose_name='Дисциплина')),
                ('regional_divisions_events', models.ManyToManyField(to='info.events', verbose_name='Мероприятия в данном регионе')),
                ('regional_divisions_regions', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='data.regions', verbose_name='Регион')),
                ('regional_divisions_сities', models.ManyToManyField(to='data.cities', verbose_name='Список городов')),
            ],
            options={
                'verbose_name': 'Региональное отделение',
                'verbose_name_plural': 'Региональные отделения',
            },
        ),
        migrations.AddField(
            model_name='news',
            name='regional_divisions',
            field=models.ManyToManyField(to='info.regionaldivisions', verbose_name='Региональные отделения'),
        ),
        migrations.CreateModel(
            name='RegisteredEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info.events', verbose_name='Мероприятие')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Зарегистрированное мероприятие',
                'verbose_name_plural': 'Зарегистрированные мероприятия',
            },
        ),
    ]
