# Generated by Django 5.0.6 on 2024-05-16 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='followersnews',
            options={'verbose_name': 'Подписчик на новость', 'verbose_name_plural': 'Подписчики на новость'},
        ),
        migrations.AlterModelOptions(
            name='registeredevents',
            options={'verbose_name': 'Зарегистрированный пользователь на мероприятие', 'verbose_name_plural': 'Зарегистрированные пользователи на мероприятия'},
        ),
        migrations.RenameField(
            model_name='news',
            old_name='autors',
            new_name='news_autors',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='disciplines',
            new_name='news_disciplines',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='regional_divisions',
            new_name='news_regional_divisions',
        ),
        migrations.RenameField(
            model_name='regionaldivisions',
            old_name='regional_divisions_curators',
            new_name='regional_divisions_curator',
        ),
        migrations.RenameField(
            model_name='regionaldivisions',
            old_name='regional_divisions_disciplines',
            new_name='regional_divisions_discipline',
        ),
        migrations.RenameField(
            model_name='regionaldivisions',
            old_name='regional_divisions_events',
            new_name='regional_divisions_event',
        ),
        migrations.RenameField(
            model_name='regionaldivisions',
            old_name='regional_divisions_regions',
            new_name='regional_divisions_region',
        ),
        migrations.RenameField(
            model_name='regionaldivisions',
            old_name='regional_divisions_сities',
            new_name='regional_divisions_сity',
        ),
    ]
