# Generated by Django 5.0.6 on 2024-05-16 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_rename_video_object_sport_objectsport_object_sport_video'),
        ('info', '0002_alter_followersnews_options_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='events_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='data.cities', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='events',
            name='events_curator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='users.users', verbose_name='Организатор мероприятия'),
        ),
        migrations.AlterField(
            model_name='events',
            name='events_disciplines',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='data.disciplines', verbose_name='Дисциплины'),
        ),
        migrations.AlterField(
            model_name='favoriteevents',
            name='events',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_by', to='info.events', verbose_name='Мероприятие'),
        ),
        migrations.AlterField(
            model_name='favoriteevents',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_events', to='users.users', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='followersnews',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_by', to='info.news', verbose_name='Новости'),
        ),
        migrations.AlterField(
            model_name='followersnews',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers_news', to='users.users', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_autors',
            field=models.ManyToManyField(related_name='news', to='users.users', verbose_name='Авторы'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_disciplines',
            field=models.ManyToManyField(related_name='news', to='data.disciplines', verbose_name='Дисциплины'),
        ),
        migrations.AlterField(
            model_name='news',
            name='news_regional_divisions',
            field=models.ManyToManyField(related_name='news', to='info.regionaldivisions', verbose_name='Региональные отделения'),
        ),
        migrations.AlterField(
            model_name='regionaldivisions',
            name='regional_divisions_curator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regional_divisions', to='users.users', verbose_name='Руководитель регионального отделения'),
        ),
        migrations.AlterField(
            model_name='regionaldivisions',
            name='regional_divisions_discipline',
            field=models.ManyToManyField(related_name='regional_divisions', to='data.disciplines', verbose_name='Дисциплина'),
        ),
        migrations.AlterField(
            model_name='regionaldivisions',
            name='regional_divisions_event',
            field=models.ManyToManyField(related_name='regional_divisions', to='info.events', verbose_name='Мероприятия в данном регионе'),
        ),
        migrations.AlterField(
            model_name='regionaldivisions',
            name='regional_divisions_region',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='regional_divisions', to='data.regions', verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='regionaldivisions',
            name='regional_divisions_сity',
            field=models.ManyToManyField(related_name='regional_divisions', to='data.cities', verbose_name='Список городов'),
        ),
        migrations.AlterField(
            model_name='registeredevents',
            name='events',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_by', to='info.events', verbose_name='Мероприятие'),
        ),
        migrations.AlterField(
            model_name='registeredevents',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_events', to='users.users', verbose_name='Пользователь'),
        ),
    ]
