# Generated by Django 5.0.6 on 2024-05-20 11:50

import core.constants
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("info", "0003_alter_events_events_city_alter_events_events_curator_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="favoriteevents",
            name="events",
        ),
        migrations.RemoveField(
            model_name="registeredevents",
            name="events",
        ),
        migrations.RemoveField(
            model_name="regionaldivisions",
            name="regional_divisions_event",
        ),
        migrations.RemoveField(
            model_name="favoriteevents",
            name="user",
        ),
        migrations.RemoveField(
            model_name="followersnews",
            name="news",
        ),
        migrations.RemoveField(
            model_name="followersnews",
            name="user",
        ),
        migrations.RemoveField(
            model_name="news",
            name="news_autors",
        ),
        migrations.RemoveField(
            model_name="news",
            name="news_disciplines",
        ),
        migrations.RemoveField(
            model_name="news",
            name="news_regional_divisions",
        ),
        migrations.RemoveField(
            model_name="registeredevents",
            name="user",
        ),
        migrations.AlterField(
            model_name="regionaldivisions",
            name="regional_divisions_title",
            field=models.CharField(
                max_length=core.constants.FieldLength["MAX_LENGTH_TITLE"],
                verbose_name="Название регионального отделения",
            ),
        ),
        migrations.DeleteModel(
            name="Events",
        ),
        migrations.DeleteModel(
            name="FavoriteEvents",
        ),
        migrations.DeleteModel(
            name="FollowersNews",
        ),
        migrations.DeleteModel(
            name="News",
        ),
        migrations.DeleteModel(
            name="RegisteredEvents",
        ),
    ]
