# Generated by Django 5.0.6 on 2024-05-20 17:49

import core.constants
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("info", "0004_remove_favoriteevents_events_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Disciplines",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "disciplines_title",
                    models.CharField(
                        max_length=core.constants.FieldLength["MAX_LENGTH_TITLE"],
                        verbose_name="Название дисциплины",
                    ),
                ),
                (
                    "disciplines_image",
                    models.ImageField(
                        upload_to="images/disciplines/",
                        verbose_name="Фотография дисциплины",
                    ),
                ),
                (
                    "disciplines_video_url",
                    models.URLField(blank=True, verbose_name="Ссылка на видео"),
                ),
                (
                    "disciplines_information",
                    models.TextField(verbose_name="Информация о дисциплине"),
                ),
            ],
            options={
                "verbose_name": "Дисциплина",
                "verbose_name_plural": "Дисциплины",
            },
        ),
        migrations.CreateModel(
            name="ObjectSportImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "object_sport_image",
                    models.ImageField(
                        upload_to="images/object_sport/",
                        verbose_name="Фотография спортивного обьекта",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фотография спортивного обьекта",
                "verbose_name_plural": "Фотография спортивных обьектов",
            },
        ),
        migrations.CreateModel(
            name="Partners",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "partners_title",
                    models.CharField(
                        max_length=core.constants.FieldLength["MAX_LENGTH_TITLE"],
                        verbose_name="Название партнера",
                    ),
                ),
                (
                    "partners_category",
                    models.CharField(
                        choices=[
                            ("strategic", "Стратегические партнеры"),
                            ("organizational", "Организационные партнеры"),
                            ("regional", "Региональные партнеры"),
                            ("general", "Генеральные партнеры"),
                        ],
                        default="strategic",
                        max_length=core.constants.FieldLength["MAX_LENGTH_TITLE"],
                        verbose_name="Категория партнера",
                    ),
                ),
                (
                    "partners_logo",
                    models.ImageField(
                        upload_to="images/partners/", verbose_name="Логотип партнера"
                    ),
                ),
                (
                    "partners_url",
                    models.URLField(blank=True, verbose_name="Ссылка на сайт партнера"),
                ),
            ],
            options={
                "verbose_name": "Партнер",
                "verbose_name_plural": "Партнеры",
            },
        ),
        migrations.AlterField(
            model_name="regionaldivisions",
            name="regional_divisions_discipline",
            field=models.ManyToManyField(
                related_name="regional_divisions",
                to="info.disciplines",
                verbose_name="Дисциплина",
            ),
        ),
        migrations.CreateModel(
            name="ObjectSport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "object_sport_title",
                    models.CharField(
                        max_length=core.constants.FieldLength["MAX_LENGTH_TITLE"],
                        verbose_name="Название спортивного объекта",
                    ),
                ),
                (
                    "object_sport_video",
                    models.URLField(verbose_name="Ссылка на видео объекта спорта"),
                ),
                (
                    "object_sport_type",
                    models.CharField(
                        choices=[("outdoor", "Открытое"), ("indoor", "Закрытое")],
                        default="indoor",
                        max_length=core.constants.FieldLength["MAX_LENGTH_TITLE"],
                        verbose_name="Помещение (закрытое/открытое)",
                    ),
                ),
                (
                    "object_sport_info",
                    models.TextField(verbose_name="Описание объекта"),
                ),
                (
                    "object_sport_address",
                    models.CharField(
                        max_length=core.constants.FieldLength["MAX_LENGTH_TITLE"],
                        verbose_name="Адрес обьекта",
                    ),
                ),
                (
                    "object_disciplines",
                    models.ManyToManyField(
                        to="info.disciplines", verbose_name="Дисциплины объекта"
                    ),
                ),
                (
                    "object_sport_image",
                    models.ManyToManyField(
                        to="info.objectsportimage",
                        verbose_name="Фотография спортивного обьекта",
                    ),
                ),
            ],
            options={
                "verbose_name": "Спортивный объект",
                "verbose_name_plural": "Спортивные объекты",
            },
        ),
        migrations.AddField(
            model_name="regionaldivisions",
            name="regional_divisions_sport_obj",
            field=models.ManyToManyField(
                related_name="regional_sport_objects",
                to="info.objectsport",
                verbose_name="Спортивные объекты",
            ),
        ),
    ]
