# Generated by Django 5.0.6 on 2024-05-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("info", "0005_disciplines_objectsportimage_partners_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="objectsport",
            name="object_sport_video",
            field=models.URLField(
                blank=True, verbose_name="Ссылка на видео объекта спорта"
            ),
        ),
    ]
