# Generated by Django 5.0.6 on 2024-05-21 13:27

import core.constants
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('info', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='дата обновления')),
                ('news_title', models.CharField(max_length=core.constants.FieldLength['MAX_LENGTH_TITLE'], verbose_name='Название новости')),
                ('news_image', models.ImageField(upload_to='images/news/', verbose_name='Фотография к новости')),
                ('news_text', models.TextField(verbose_name='Описание новости')),
                ('news_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_author', to=settings.AUTH_USER_MODEL, verbose_name='Автор новости')),
                ('news_disciplines', models.ManyToManyField(related_name='news', to='info.disciplines', verbose_name='Дисциплины')),
                ('news_regional_divisions', models.ManyToManyField(related_name='news', to='info.regionaldivisions', verbose_name='Региональные отделения')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-created_at'],
            },
        ),
    ]
