# Generated by Django 5.0.6 on 2024-05-26 18:47

import core.constants
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, db_index=True, verbose_name="дата обновления"
                    ),
                ),
                (
                    "news_title",
                    models.CharField(
                        max_length=core.constants.FieldLength["MAX_LENGTH_TITLE"],
                        verbose_name="Название новости",
                    ),
                ),
                (
                    "news_image",
                    models.ImageField(
                        upload_to="images/news/", verbose_name="Фотография к новости"
                    ),
                ),
                ("news_text", models.TextField(verbose_name="Описание новости")),
            ],
            options={
                "verbose_name": "Новость",
                "verbose_name_plural": "Новости",
                "ordering": ["-created_at"],
            },
        ),
    ]
