# Generated by Django 5.0.6 on 2024-05-26 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("info", "0002_initial"),
        ("news", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="news_author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="news_author",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор новости",
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="news_disciplines",
            field=models.ManyToManyField(
                related_name="news", to="info.disciplines", verbose_name="Дисциплины"
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="news_regional_divisions",
            field=models.ManyToManyField(
                related_name="news",
                to="info.regionaldivisions",
                verbose_name="Региональные отделения",
            ),
        ),
    ]
