# Generated by Django 5.0.6 on 2024-05-26 21:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="news_reading_time",
            field=models.IntegerField(
                default=5, verbose_name="Время на чтение (в минутах)"
            ),
        ),
    ]
