# Generated by Django 5.0.6 on 2024-05-27 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0001_initial"),
        ("news", "0003_news_news_reading_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="event_city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="news",
                to="data.cities",
                verbose_name="Город",
            ),
        ),
    ]
