# Generated by Django 5.0.6 on 2024-05-16 18:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='Логин')),
                ('password', models.CharField(max_length=100, verbose_name='Пароль')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('middle_name', models.CharField(max_length=100, verbose_name='Отчество')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('account_status', models.CharField(choices=[('user', 'Пользователь'), ('member', 'Участник'), ('curator', 'Куратор'), ('regional_leader', 'Региональный руководитель'), ('central_leadership', 'Центральное руководство')], default='user', max_length=20, verbose_name='Статус аккаунта')),
                ('birth_year', models.DateField(verbose_name='Дата рождения')),
                ('career_start', models.DateField(verbose_name='Дата начала карьеры')),
                ('biography', models.TextField(verbose_name='Биография')),
                ('passport_series', models.IntegerField(validators=[django.core.validators.RegexValidator('^\\d{1,10}$', message='Only digits are allowed')], verbose_name='Серия паспорта')),
                ('passport_number', models.IntegerField(validators=[django.core.validators.RegexValidator('^\\d{1,20}$', message='Only digits are allowed')], verbose_name='Номер паспорта')),
                ('passport_issued_by', models.CharField(max_length=100, verbose_name='Кем выдан паспорт')),
                ('vk_link', models.URLField(verbose_name='Ссылка на ВК')),
                ('video_profile', models.FileField(upload_to='video_profiles/', verbose_name='Видеовизитка')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
