# Generated by Django 5.0.6 on 2024-05-20 11:50

import core.constants
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="passport_issued_by",
        ),
        migrations.RemoveField(
            model_name="users",
            name="passport_number",
        ),
        migrations.RemoveField(
            model_name="users",
            name="passport_series",
        ),
        migrations.AlterField(
            model_name="users",
            name="email",
            field=models.EmailField(
                max_length=core.constants.UserFieldsLength["MAX_LENGTH_USERNAME"],
                verbose_name="Электронная почта",
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="first_name",
            field=models.CharField(
                max_length=core.constants.UserFieldsLength["MAX_LENGTH_USERNAME"],
                verbose_name="Имя",
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="last_name",
            field=models.CharField(
                max_length=core.constants.UserFieldsLength["MAX_LENGTH_USERNAME"],
                verbose_name="Фамилия",
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="middle_name",
            field=models.CharField(
                max_length=core.constants.UserFieldsLength["MAX_LENGTH_USERNAME"],
                verbose_name="Отчество",
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="password",
            field=models.CharField(
                max_length=core.constants.UserFieldsLength["MAX_LENGTH_USERNAME"],
                verbose_name="Пароль",
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="phone",
            field=models.CharField(
                max_length=core.constants.UserFieldsLength["MAX_LENGTH_NUMBER"],
                verbose_name="Телефон",
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="position",
            field=models.CharField(
                max_length=core.constants.UserFieldsLength["MAX_LENGTH_USERNAME"],
                verbose_name="Должность",
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="username",
            field=models.CharField(
                max_length=core.constants.UserFieldsLength["MAX_LENGTH_USERNAME"],
                verbose_name="Логин",
            ),
        ),
        migrations.CreateModel(
            name="UserPassport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "passport_series",
                    models.IntegerField(
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{1,10}$", message="Only digits are allowed"
                            )
                        ],
                        verbose_name="Серия паспорта",
                    ),
                ),
                (
                    "passport_number",
                    models.IntegerField(
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{1,20}$", message="Only digits are allowed"
                            )
                        ],
                        verbose_name="Номер паспорта",
                    ),
                ),
                (
                    "passport_issued_by",
                    models.CharField(
                        max_length=core.constants.UserFieldsLength[
                            "MAX_LENGTH_USERNAME"
                        ],
                        verbose_name="Кем выдан паспорт",
                    ),
                ),
                ("passport_issued_at", models.DateField(verbose_name="Дата выдачи")),
                (
                    "accept_rules",
                    models.BooleanField(
                        default=False,
                        verbose_name="Cогласие с правами и обязанностями участника",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="passport",
                        to="users.users",
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Инфо о паспорте пользователя",
                "verbose_name_plural": "Инфо о паспортах пользователей",
                "ordering": ["-pk"],
            },
        ),
    ]
