# Generated by Django 5.0.6 on 2024-05-20 13:44

import datetime

import core.constants
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_users_managers_users_date_joined_users_groups_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="biography",
            field=models.TextField(blank=True, verbose_name="Биография"),
        ),
        migrations.AlterField(
            model_name="users",
            name="birth_year",
            field=models.DateField(
                default=datetime.date.today, verbose_name="Дата рождения"
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="career_start",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата начала карьеры"
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="position",
            field=models.CharField(
                blank=True,
                max_length=core.constants.UserFieldsLength["MAX_LENGTH_USERNAME"],
                verbose_name="Должность",
            ),
        ),
    ]
