# Generated by Django 5.0.6 on 2024-05-20 18:19

import core.constants
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_users_biography_alter_users_birth_year_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userpassport",
            name="passport_issued_at",
            field=models.DateField(default="", verbose_name="Дата выдачи"),
        ),
        migrations.AlterField(
            model_name="userpassport",
            name="passport_issued_by",
            field=models.CharField(
                default="",
                max_length=core.constants.UserFieldsLength["MAX_LENGTH_USERNAME"],
                verbose_name="Кем выдан паспорт",
            ),
        ),
        migrations.AlterField(
            model_name="userpassport",
            name="passport_number",
            field=models.PositiveIntegerField(
                default="", verbose_name="Номер паспорта"
            ),
        ),
        migrations.AlterField(
            model_name="userpassport",
            name="passport_series",
            field=models.PositiveIntegerField(
                default="", verbose_name="Серия паспорта"
            ),
        ),
    ]
