# Generated by Django 5.0.6 on 2024-05-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_userpassport_passport_issued_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="photo",
            field=models.ImageField(
                blank=True,
                default=None,
                null=True,
                upload_to="users/images/",
                verbose_name="Фото",
            ),
        ),
    ]
